// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kasvusvzrphjjfvsbonp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthc3Z1c3Z6cnBoampmdnNib25wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyOTg3MjQsImV4cCI6MjA1MTg3NDcyNH0.6W7f8Lerj1UaOxkfBGLffW07z9VWA3b-4oYjrscRpcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);